### ISSUE TITLE
Warnings in Xcode 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-ios#4]
![voila_capture 2016-08-05_10-09-42_am](https://cloud.githubusercontent.com/assets/43789/17432036/e0e4a5c6-5af4-11e6-8c41-8e6c9199db4e.png)

**Comment by stannedelchev** [comment]
I think the first two warnings should be cleared by referencing the files in the library [here](https://github.com/ably/ably-ios/blob/master/Source/AblyRealtime.h). @tcard , can you confirm this?
The third warning is fixed in 1acdd0006f82345d1069be94c79a0018ad679767.

**Comment by tcard** [comment]
Fixed by https://github.com/ably/ably-ios/commit/150dd7e.
